### ISSUE TITLE
Add Github Actions for CI

### ISSUE THREAD

**Issue by chrisjm** [chrisjm/openbrewerydb-rails-api#28]
## Overview

It's been a while, but I think we were using Travis CI for the continuous integration (CI). 

Continuous deployment (CD) is handled by Heroku, but isn't currently working because CI isn't set up.

## Tasks

- [x] Add Github Actions for testing repo
- [x] Remove `.travis.yml`
- [x] Update README
- [x] Update build status badge

## Implementation Notes

- This [Stack Overflow answer](https://stackoverflow.com/questions/57915791/how-to-connect-to-postgres-in-githhub-actions) was very helpful in figuring out how to set up PostgreSQL in a container.
